export const color = {
  primary: '#2BA0F3',
  primaryDark: '#00244c',
  green: 'green',
  red: 'red',
  white: 'white',
  navigationBarText: 'white',
  drawerIconColor: 'gray',
  textWhite: 'white',
  textBlack: 'black',
  textGray: '#3f3c38',
  myGreen: '#26af4f',
  materialGreen: '#00ab9c',
  myGray: '#3f3c38',
  skillItemColor: '#E4E4E4',
};
